### ISSUE TITLE
网络请求问题

### ISSUE THREAD

**Issue by Raysuner** [tonori/imooc-jira#1]
请问以下，就是老师用了分布式后端后，我按照视频内容来的向3001端口/register发送请求总是失败，你有碰到过这个问题吗

**Comment by chisaki-takahashi** [comment]
我直接请求 localhost:3000 也出现了 404，加了一个非同域的域名就好了
`localhost:3000/register -> api.jira.com/register`

**Comment by Raysuner** [comment]
localhost:3000是react开的服务器，请求当然是404。课上老师用的是3001号端口，我这发图片不方便，能不能加个qq或者微信，我卡这卡一天了，我qq 1669232805
